# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chasing ignorabimus
email: do@danielobolensky.me
description: >- # this means to ignore newlines until "baseurl:"
  Corner of the internet where I host my projects and thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielobolensky.me" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  houdinied

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  blog:
    output: true
    permalink: /:collection/:name/

# Automatically assign tags by collection/type so we don't edit each post
defaults:
  # All regular posts get tagged as 'blog'
  - scope:
      path: ""
      type: "posts"
    values:
      tags: ["blog"]
  # All items in the custom 'blog' collection also get 'blog'
  - scope:
      path: ""
      type: "blog"
    values:
      tags: ["blog"]
  # All items in the 'projects' collection get 'project'
  - scope:
      path: ""
      type: "projects"
    values:
      tags: ["project"]

# Header navigation links (Minima)
header_pages:
  - blog.md
  - projects.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
